### ISSUE TITLE
Packageconfig parser parses with "

### ISSUE THREAD

**Issue by ThomCoder** [ThomCoder/Install_A_Bot#13]
An entry in the packages.toml file might read literally
```toml
    install_cmd = "sudo apt install"
```
In that case the packageconfig parser would parse the string **"**sudo apt install**"** (with the quotes).
When afterwards the install_cmd gets passed to the target system's command line it will also get inserted with the quotes.

Then on e.g. bash the quoted string gets treated as a single entity making up a command but obviously the command
`sudo apt install` (as one string) does not exist.

Steps to reproduce:
- Copy the file util/packages_linux.toml into the project root as packages.toml
- Start the Docker container with `cd util && ./docker_build.sh && ./docker_run.sh"
- Inside the container run `cargo build`
- Then run the executable; the main thread will panic.

Now we must decide if we want to adapt the packageconfig parser or if we want to split the string in the individual backends.
I suggest the first one to avoid duplicating work.

**Comment by theswiftfox** [comment]
thats defenitely a bug.
i will fix the package config parser to remove leading and trailing "

**Comment by theswiftfox** [comment]
After checking the code, the issue is in the systemconfig parser. 
I don't think we want to support having an install_cmd in a package target. (custom install_cmds for a package are a different topic)
